all: start
scalar_product: scalar_product.c
	gcc -w -o scalar_product scalar_product.c
prime_number_checker: prime_number_checker.c
	gcc -w -o prime_number_checker prime_number_checker.c

start: prime_number_checker scalar_product